using BaseLib.Utils;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.ValueProps;

namespace WatcherRebalance.WatcherRebalanceCode.Cards.Token.New;


// ============================================================================
// SHARED BLASPHEMY JUDGEMENT TOKEN
// ============================================================================
//
// These cards are generated by Blasphemy's hidden punishment.
//
// Multiplayer safety:
//
// - NO Random.Shared.
// - NO SemaphoreSlim.
// - NO Task.Delay controlling game logic.
// - Damage is deterministic from the Judgement card's type.
// - The game itself controls OnTurnEndInHand sequencing.
//
// All Judgements:
//
// - Are Token rarity.
// - Belong to TokenCardPool.
// - Are hidden from the Card Library.
// - Can still be explicitly generated during combat.
// - Resolve automatically at end of turn.
// - Deal approximately 10% of Max HP.
// - Individual Judgements vary from roughly 80% to 120%.
// - Non-final Judgements cannot kill the player.
// - The final Judgement deals all remaining HP.
// - Ignore Block.
// - Ignore Intangible.
// - Ignore Buffer without consuming it.
// ============================================================================

public abstract class BlasphemyJudgementCard()
    : WatcherRebalanceCard(
        0,
        CardType.Skill,
        CardRarity.Token,
        TargetType.Self,
        shouldShowInCardLibrary: false)
{
    // ========================================================================
    // GENERATION
    // ========================================================================
    //
    // These are hidden Tokens, but unlike retired vanilla cards they MUST
    // remain generatable because Blasphemy explicitly creates them.
    // ========================================================================

    public override bool CanBeGeneratedInCombat =>
        true;


    // ========================================================================
    // TURN-END EFFECT
    // ========================================================================

    public override bool HasTurnEndInHandEffect =>
        true;


    // ========================================================================
    // KEYWORDS
    // ========================================================================

    public override IEnumerable<CardKeyword> CanonicalKeywords =>
    [
        CardKeyword.Exhaust
    ];


    // ========================================================================
    // DAMAGE MULTIPLIER
    // ========================================================================
    //
    // IMPORTANT:
    //
    // Do not use Random.Shared here.
    //
    // STS2 multiplayer requires gameplay state to resolve identically on
    // every peer. Random.Shared is local process state and therefore can
    // produce different damage values on different machines.
    //
    // Instead, each named Judgement has a fixed multiplier.
    //
    // Across the ten cards these range from:
    //
    //     0.80x -> 1.20x
    //
    // so the overall feel of the old randomized damage is retained without
    // requiring any unsynchronized randomness.
    // ========================================================================

    protected abstract decimal DamageMultiplier { get; }


    // ========================================================================
    // NORMAL PLAY
    // ========================================================================
    //
    // These are not intended to be manually played.
    //
    // This remains as a fallback if another effect somehow forces one to
    // resolve as a normal card play.
    // ========================================================================

    protected override Task OnPlay(
        PlayerChoiceContext choiceContext,
        CardPlay cardPlay)
    {
        return ResolveJudgement(
            choiceContext);
    }


    // ========================================================================
    // END-OF-TURN RESOLUTION
    // ========================================================================
    //
    // CardModel's turn-end system already moves the currently resolving card
    // into the Play pile while OnTurnEndInHand runs.
    //
    // We therefore do NOT add our own SemaphoreSlim or scheduling mechanism.
    //
    // Multiplayer/game-action sequencing should remain under STS2's control.
    // ========================================================================

    protected override Task OnTurnEndInHand(
        PlayerChoiceContext choiceContext)
    {
        return ResolveJudgement(
            choiceContext);
    }


    // ========================================================================
    // RESOLVE JUDGEMENT
    // ========================================================================

    private async Task ResolveJudgement(
        PlayerChoiceContext choiceContext)
    {
        Creature creature =
            Owner.Creature;


        // --------------------------------------------------------------------
        // DEAD PLAYER
        // --------------------------------------------------------------------

        if (!creature.IsAlive)
            return;


        CardPile hand =
            PileType.Hand.GetPile(
                Owner);


        // ====================================================================
        // CHECK FOR ANOTHER JUDGEMENT
        // ====================================================================
        //
        // The currently resolving Judgement is in the Play pile.
        //
        // If another Blasphemy Judgement remains in Hand, this is NOT the
        // final one.
        //
        // We intentionally check specifically for Judgement cards instead of
        // hand.Cards.Count.
        //
        // This means ordinary retained cards do not interfere with deciding
        // which Judgement is the final punishment.
        // ====================================================================

        bool anotherJudgementRemains =
            hand.Cards.Any(
                card =>
                    card is BlasphemyJudgementCard);


        decimal damage;


        // ====================================================================
        // FINAL JUDGEMENT
        // ====================================================================

        if (!anotherJudgementRemains)
        {
            damage =
                creature.CurrentHp;
        }


        // ====================================================================
        // NORMAL JUDGEMENT
        // ====================================================================

        else
        {
            // ----------------------------------------------------------------
            // BASE DAMAGE
            //
            // Approximately 10% Max HP.
            // ----------------------------------------------------------------

            decimal baseDamage =
                Math.Floor(
                    creature.MaxHp / 10m);


            // ----------------------------------------------------------------
            // DETERMINISTIC VARIATION
            // ----------------------------------------------------------------

            damage =
                Math.Floor(
                    baseDamage *
                    DamageMultiplier);


            // At least 1 damage when possible.
            damage =
                Math.Max(
                    1m,
                    damage);


            // ----------------------------------------------------------------
            // NEVER KILL EARLY
            // ----------------------------------------------------------------
            //
            // Every non-final Judgement leaves the player at 1 HP minimum.
            // ----------------------------------------------------------------

            decimal maximumAllowedDamage =
                Math.Max(
                    0m,
                    creature.CurrentHp - 1m);


            damage =
                Math.Min(
                    damage,
                    maximumAllowedDamage);
        }


        // ====================================================================
        // NOTHING TO DEAL
        // ====================================================================

        if (damage <= 0m)
            return;


        // ====================================================================
        // VFX / SFX
        // ====================================================================
        //
        // These are fired immediately.
        //
        // There is deliberately no Task.Delay here. Local timing should not
        // influence when subsequent combat-state mutations occur.
        // ====================================================================

        VfxCmd.PlayOnCreature(
            creature,
            "vfx/vfx_attack_lightning");


        SfxCmd.Play(
            "event:/sfx/characters/defect/defect_lightning_evoke");


        // ====================================================================
        // DAMAGE
        // ====================================================================

        await CreatureCmd.Damage(
            choiceContext,
            creature,
            damage,
            ValueProp.Unpowered |
            ValueProp.Unblockable,
            this,
            null);
    }
}


// ============================================================================
// THE TEN JUDGEMENTS
// ============================================================================
//
// Fixed deterministic multipliers:
//
// Unworthy    0.80
// Traitor     0.85
// Repent      0.90
// Forsaken    0.95
// Heretic     1.00
// Apostate    1.00
// Profane     1.05
// Condemned   1.10
// Unforgiven  1.15
// Judgement   1.20
//
// Which names Blasphemy creates can still provide apparent damage variation,
// but every peer will calculate exactly the same damage from the same card.
// ============================================================================


[Pool(typeof(TokenCardPool))]
public sealed class Unworthy
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        0.80m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Traitor
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        0.85m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Repent
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        0.90m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Forsaken
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        0.95m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Heretic
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.00m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Apostate
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.00m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Profane
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.05m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Condemned
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.10m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Unforgiven
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.15m;
}


[Pool(typeof(TokenCardPool))]
public sealed class Judgement
    : BlasphemyJudgementCard
{
    protected override decimal DamageMultiplier =>
        1.20m;
}