using BaseLib.Utils;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.ValueProps;
using Watcher.Code.Character;

namespace WatcherRebalance.WatcherRebalanceCode.Cards.Token.New;


// =============================================================
// SHARED BLASPHEMY JUDGEMENT TOKEN
// =============================================================
//
// These cards are generated by Blasphemy's hidden punishment.
//
// They:
//
// - Are Token rarity.
// - Belong to the Watcher card pool.
// - Do NOT appear in the card library.
// - All use judgement.png as their artwork.
// - Remain in Hand until the player ends their turn.
// - Resolve automatically at end of turn.
// - Resolve strictly one at a time.
// - Deal approximately 10% of Max HP.
// - Randomize normal hits between 80% and 120%.
// - Cannot kill the player before the final Judgement.
// - Deal all remaining HP when no other cards remain in Hand.
// - Ignore Block.
// - Ignore Intangible.
// - Ignore Buffer without consuming it.
// - Use the Defect Lightning Orb evoke VFX and SFX.
// =============================================================

public abstract class BlasphemyJudgementCard()
    : WatcherRebalanceCard(
        0,
        CardType.Skill,
        CardRarity.Token,
        TargetType.Self,
        shouldShowInCardLibrary: false)
{
    // =========================================================
    // SEQUENTIAL RESOLUTION LOCK
    // =========================================================
    //
    // Only one Judgement is allowed to resolve at a time.
    //
    // Even if STS2 starts multiple turn-end card effects
    // concurrently, every Judgement must wait until the
    // previous one has completely finished.
    // =========================================================

    private static readonly SemaphoreSlim JudgementLock =
        new(1, 1);
    

    // =========================================================
    // TURN-END HAND EFFECT
    // =========================================================

    public override bool HasTurnEndInHandEffect =>
        true;


    // =========================================================
    // KEYWORDS
    // =========================================================

    public override IEnumerable<CardKeyword> CanonicalKeywords =>
    [
        CardKeyword.Exhaust
    ];


    // =========================================================
    // NORMAL PLAY
    // =========================================================
    //
    // These aren't intended to be manually played.
    //
    // This remains as a fallback in case another effect
    // somehow forces one to be played.
    // =========================================================

    protected override async Task OnPlay(
        PlayerChoiceContext choiceContext,
        CardPlay cardPlay)
    {
        await ResolveJudgement(
            choiceContext);
    }


    // =========================================================
    // END-OF-TURN RESOLUTION
    // =========================================================
    //
    // This is the intended way Judgements resolve.
    //
    // The player can inspect them for their entire turn.
    //
    // Once End Turn is pressed, each Judgement waits until
    // the previous one has completely finished.
    // =========================================================

    protected override async Task OnTurnEndInHand(
        PlayerChoiceContext choiceContext)
    {
        await JudgementLock.WaitAsync();

        try
        {
            // Fully resolve this Judgement.
            await ResolveJudgement(
                choiceContext);
            
        }
        finally
        {
            JudgementLock.Release();
        }
    }


    // =========================================================
    // RESOLVE JUDGEMENT
    // =========================================================

    private async Task ResolveJudgement(
        PlayerChoiceContext choiceContext)
    {
        Creature creature =
            Owner.Creature;


        // Don't attempt further Judgements once the player
        // has died.
        if (!creature.IsAlive)
            return;


        CardPile hand =
            PileType.Hand.GetPile(
                Owner);


        decimal damage;


        // =====================================================
        // FINAL JUDGEMENT
        // =====================================================
        //
        // During turn-end processing, the currently resolving
        // Judgement has already left the Hand.
        //
        // Therefore, if nothing else remains in Hand, this is
        // the final Judgement.
        //
        // It deals exactly the player's remaining HP.
        // =====================================================

        if (hand.Cards.Count == 0)
        {
            damage =
                creature.CurrentHp;
        }


        // =====================================================
        // NORMAL JUDGEMENT
        // =====================================================

        else
        {
            // -------------------------------------------------
            // BASE DAMAGE
            // -------------------------------------------------
            //
            // Approximately 10% of Max HP.
            // -------------------------------------------------

            int baseDamage =
                (int)Math.Floor(
                    creature.MaxHp / 10m);


            // -------------------------------------------------
            // RANDOM DAMAGE RANGE
            // -------------------------------------------------
            //
            // 80% to 120% of the base value.
            // -------------------------------------------------

            int minimumDamage =
                Math.Max(
                    1,
                    (int)Math.Floor(
                        baseDamage * 0.8m));


            int maximumDamage =
                Math.Max(
                    minimumDamage,
                    (int)Math.Floor(
                        baseDamage * 1.2m));


            damage =
                Random.Shared.Next(
                    minimumDamage,
                    maximumDamage + 1);


            // -------------------------------------------------
            // NEVER KILL EARLY
            // -------------------------------------------------
            //
            // Every non-final Judgement must leave the player
            // with at least 1 HP.
            // -------------------------------------------------

            decimal maximumAllowedDamage =
                Math.Max(
                    0m,
                    creature.CurrentHp - 1m);


            damage =
                Math.Min(
                    damage,
                    maximumAllowedDamage);
        }


        // =====================================================
        // DEFECT LIGHTNING ORB EVOKE VFX
        // =====================================================

        VfxCmd.PlayOnCreature(
            creature,
            "vfx/vfx_attack_lightning");


        SfxCmd.Play(
            "event:/sfx/characters/defect/defect_lightning_evoke");


        // Give the lightning a moment to visibly land.
        await Task.Delay(150);


        // =====================================================
        // DEAL JUDGEMENT DAMAGE
        // =====================================================
        //
        // Unpowered:
        //     Don't modify the amount through normal powered
        //     damage scaling.
        //
        // Unblockable:
        //     Completely bypass Block.
        //
        // =====================================================

        await CreatureCmd.Damage(
            choiceContext,
            creature,
            damage,
            ValueProp.Unpowered | ValueProp.Unblockable,
            this,
            null);
    }
}

// =============================================================
// THE TEN JUDGEMENTS
// =============================================================


[Pool(typeof(WatcherCardPool))]
public sealed class Unworthy
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Traitor
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Repent
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Forsaken
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Heretic
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Apostate
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Profane
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Condemned
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Unforgiven
    : BlasphemyJudgementCard
{
}


[Pool(typeof(WatcherCardPool))]
public sealed class Judgement
    : BlasphemyJudgementCard
{
}